/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tongbaotu.fits.thrift.idl;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class AccountProductInfoStruct implements org.apache.thrift.TBase<AccountProductInfoStruct, AccountProductInfoStruct._Fields>, java.io.Serializable, Cloneable, Comparable<AccountProductInfoStruct> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("AccountProductInfoStruct");

  private static final org.apache.thrift.protocol.TField ACCOUNTPRODUCTID_FIELD_DESC = new org.apache.thrift.protocol.TField("accountproductid", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PRODUCTPOSITIONINFO_FIELD_DESC = new org.apache.thrift.protocol.TField("productpositioninfo", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new AccountProductInfoStructStandardSchemeFactory());
    schemes.put(TupleScheme.class, new AccountProductInfoStructTupleSchemeFactory());
  }

  public String accountproductid; // required
  public List<AccountProductPositionInfoStruct> productpositioninfo; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ACCOUNTPRODUCTID((short)1, "accountproductid"),
    PRODUCTPOSITIONINFO((short)2, "productpositioninfo");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ACCOUNTPRODUCTID
          return ACCOUNTPRODUCTID;
        case 2: // PRODUCTPOSITIONINFO
          return PRODUCTPOSITIONINFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ACCOUNTPRODUCTID, new org.apache.thrift.meta_data.FieldMetaData("accountproductid", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PRODUCTPOSITIONINFO, new org.apache.thrift.meta_data.FieldMetaData("productpositioninfo", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, AccountProductPositionInfoStruct.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(AccountProductInfoStruct.class, metaDataMap);
  }

  public AccountProductInfoStruct() {
  }

  public AccountProductInfoStruct(
    String accountproductid,
    List<AccountProductPositionInfoStruct> productpositioninfo)
  {
    this();
    this.accountproductid = accountproductid;
    this.productpositioninfo = productpositioninfo;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public AccountProductInfoStruct(AccountProductInfoStruct other) {
    if (other.isSetAccountproductid()) {
      this.accountproductid = other.accountproductid;
    }
    if (other.isSetProductpositioninfo()) {
      List<AccountProductPositionInfoStruct> __this__productpositioninfo = new ArrayList<AccountProductPositionInfoStruct>(other.productpositioninfo.size());
      for (AccountProductPositionInfoStruct other_element : other.productpositioninfo) {
        __this__productpositioninfo.add(new AccountProductPositionInfoStruct(other_element));
      }
      this.productpositioninfo = __this__productpositioninfo;
    }
  }

  public AccountProductInfoStruct deepCopy() {
    return new AccountProductInfoStruct(this);
  }

  @Override
  public void clear() {
    this.accountproductid = null;
    this.productpositioninfo = null;
  }

  public String getAccountproductid() {
    return this.accountproductid;
  }

  public AccountProductInfoStruct setAccountproductid(String accountproductid) {
    this.accountproductid = accountproductid;
    return this;
  }

  public void unsetAccountproductid() {
    this.accountproductid = null;
  }

  /** Returns true if field accountproductid is set (has been assigned a value) and false otherwise */
  public boolean isSetAccountproductid() {
    return this.accountproductid != null;
  }

  public void setAccountproductidIsSet(boolean value) {
    if (!value) {
      this.accountproductid = null;
    }
  }

  public int getProductpositioninfoSize() {
    return (this.productpositioninfo == null) ? 0 : this.productpositioninfo.size();
  }

  public java.util.Iterator<AccountProductPositionInfoStruct> getProductpositioninfoIterator() {
    return (this.productpositioninfo == null) ? null : this.productpositioninfo.iterator();
  }

  public void addToProductpositioninfo(AccountProductPositionInfoStruct elem) {
    if (this.productpositioninfo == null) {
      this.productpositioninfo = new ArrayList<AccountProductPositionInfoStruct>();
    }
    this.productpositioninfo.add(elem);
  }

  public List<AccountProductPositionInfoStruct> getProductpositioninfo() {
    return this.productpositioninfo;
  }

  public AccountProductInfoStruct setProductpositioninfo(List<AccountProductPositionInfoStruct> productpositioninfo) {
    this.productpositioninfo = productpositioninfo;
    return this;
  }

  public void unsetProductpositioninfo() {
    this.productpositioninfo = null;
  }

  /** Returns true if field productpositioninfo is set (has been assigned a value) and false otherwise */
  public boolean isSetProductpositioninfo() {
    return this.productpositioninfo != null;
  }

  public void setProductpositioninfoIsSet(boolean value) {
    if (!value) {
      this.productpositioninfo = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ACCOUNTPRODUCTID:
      if (value == null) {
        unsetAccountproductid();
      } else {
        setAccountproductid((String)value);
      }
      break;

    case PRODUCTPOSITIONINFO:
      if (value == null) {
        unsetProductpositioninfo();
      } else {
        setProductpositioninfo((List<AccountProductPositionInfoStruct>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ACCOUNTPRODUCTID:
      return getAccountproductid();

    case PRODUCTPOSITIONINFO:
      return getProductpositioninfo();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ACCOUNTPRODUCTID:
      return isSetAccountproductid();
    case PRODUCTPOSITIONINFO:
      return isSetProductpositioninfo();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof AccountProductInfoStruct)
      return this.equals((AccountProductInfoStruct)that);
    return false;
  }

  public boolean equals(AccountProductInfoStruct that) {
    if (that == null)
      return false;

    boolean this_present_accountproductid = true && this.isSetAccountproductid();
    boolean that_present_accountproductid = true && that.isSetAccountproductid();
    if (this_present_accountproductid || that_present_accountproductid) {
      if (!(this_present_accountproductid && that_present_accountproductid))
        return false;
      if (!this.accountproductid.equals(that.accountproductid))
        return false;
    }

    boolean this_present_productpositioninfo = true && this.isSetProductpositioninfo();
    boolean that_present_productpositioninfo = true && that.isSetProductpositioninfo();
    if (this_present_productpositioninfo || that_present_productpositioninfo) {
      if (!(this_present_productpositioninfo && that_present_productpositioninfo))
        return false;
      if (!this.productpositioninfo.equals(that.productpositioninfo))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(AccountProductInfoStruct other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetAccountproductid()).compareTo(other.isSetAccountproductid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAccountproductid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accountproductid, other.accountproductid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetProductpositioninfo()).compareTo(other.isSetProductpositioninfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProductpositioninfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.productpositioninfo, other.productpositioninfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("AccountProductInfoStruct(");
    boolean first = true;

    sb.append("accountproductid:");
    if (this.accountproductid == null) {
      sb.append("null");
    } else {
      sb.append(this.accountproductid);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("productpositioninfo:");
    if (this.productpositioninfo == null) {
      sb.append("null");
    } else {
      sb.append(this.productpositioninfo);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (accountproductid == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'accountproductid' was not present! Struct: " + toString());
    }
    if (productpositioninfo == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'productpositioninfo' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class AccountProductInfoStructStandardSchemeFactory implements SchemeFactory {
    public AccountProductInfoStructStandardScheme getScheme() {
      return new AccountProductInfoStructStandardScheme();
    }
  }

  private static class AccountProductInfoStructStandardScheme extends StandardScheme<AccountProductInfoStruct> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, AccountProductInfoStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ACCOUNTPRODUCTID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.accountproductid = iprot.readString();
              struct.setAccountproductidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PRODUCTPOSITIONINFO
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list16 = iprot.readListBegin();
                struct.productpositioninfo = new ArrayList<AccountProductPositionInfoStruct>(_list16.size);
                for (int _i17 = 0; _i17 < _list16.size; ++_i17)
                {
                  AccountProductPositionInfoStruct _elem18;
                  _elem18 = new AccountProductPositionInfoStruct();
                  _elem18.read(iprot);
                  struct.productpositioninfo.add(_elem18);
                }
                iprot.readListEnd();
              }
              struct.setProductpositioninfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, AccountProductInfoStruct struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.accountproductid != null) {
        oprot.writeFieldBegin(ACCOUNTPRODUCTID_FIELD_DESC);
        oprot.writeString(struct.accountproductid);
        oprot.writeFieldEnd();
      }
      if (struct.productpositioninfo != null) {
        oprot.writeFieldBegin(PRODUCTPOSITIONINFO_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.productpositioninfo.size()));
          for (AccountProductPositionInfoStruct _iter19 : struct.productpositioninfo)
          {
            _iter19.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class AccountProductInfoStructTupleSchemeFactory implements SchemeFactory {
    public AccountProductInfoStructTupleScheme getScheme() {
      return new AccountProductInfoStructTupleScheme();
    }
  }

  private static class AccountProductInfoStructTupleScheme extends TupleScheme<AccountProductInfoStruct> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, AccountProductInfoStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.accountproductid);
      {
        oprot.writeI32(struct.productpositioninfo.size());
        for (AccountProductPositionInfoStruct _iter20 : struct.productpositioninfo)
        {
          _iter20.write(oprot);
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, AccountProductInfoStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.accountproductid = iprot.readString();
      struct.setAccountproductidIsSet(true);
      {
        org.apache.thrift.protocol.TList _list21 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.productpositioninfo = new ArrayList<AccountProductPositionInfoStruct>(_list21.size);
        for (int _i22 = 0; _i22 < _list21.size; ++_i22)
        {
          AccountProductPositionInfoStruct _elem23;
          _elem23 = new AccountProductPositionInfoStruct();
          _elem23.read(iprot);
          struct.productpositioninfo.add(_elem23);
        }
      }
      struct.setProductpositioninfoIsSet(true);
    }
  }

}

