/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tongbaotu.fits.thrift.idl;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class BankSignResultStruct implements org.apache.thrift.TBase<BankSignResultStruct, BankSignResultStruct._Fields>, java.io.Serializable, Cloneable, Comparable<BankSignResultStruct> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BankSignResultStruct");

  private static final org.apache.thrift.protocol.TField INVEST_SPECIAL_ACCOUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("invest_special_account", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField RET_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("retInfo", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new BankSignResultStructStandardSchemeFactory());
    schemes.put(TupleScheme.class, new BankSignResultStructTupleSchemeFactory());
  }

  public String invest_special_account; // required
  public ResultInfoStruct retInfo; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    INVEST_SPECIAL_ACCOUNT((short)1, "invest_special_account"),
    RET_INFO((short)2, "retInfo");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // INVEST_SPECIAL_ACCOUNT
          return INVEST_SPECIAL_ACCOUNT;
        case 2: // RET_INFO
          return RET_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.INVEST_SPECIAL_ACCOUNT, new org.apache.thrift.meta_data.FieldMetaData("invest_special_account", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.RET_INFO, new org.apache.thrift.meta_data.FieldMetaData("retInfo", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ResultInfoStruct.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BankSignResultStruct.class, metaDataMap);
  }

  public BankSignResultStruct() {
  }

  public BankSignResultStruct(
    String invest_special_account,
    ResultInfoStruct retInfo)
  {
    this();
    this.invest_special_account = invest_special_account;
    this.retInfo = retInfo;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BankSignResultStruct(BankSignResultStruct other) {
    if (other.isSetInvest_special_account()) {
      this.invest_special_account = other.invest_special_account;
    }
    if (other.isSetRetInfo()) {
      this.retInfo = new ResultInfoStruct(other.retInfo);
    }
  }

  public BankSignResultStruct deepCopy() {
    return new BankSignResultStruct(this);
  }

  @Override
  public void clear() {
    this.invest_special_account = null;
    this.retInfo = null;
  }

  public String getInvest_special_account() {
    return this.invest_special_account;
  }

  public BankSignResultStruct setInvest_special_account(String invest_special_account) {
    this.invest_special_account = invest_special_account;
    return this;
  }

  public void unsetInvest_special_account() {
    this.invest_special_account = null;
  }

  /** Returns true if field invest_special_account is set (has been assigned a value) and false otherwise */
  public boolean isSetInvest_special_account() {
    return this.invest_special_account != null;
  }

  public void setInvest_special_accountIsSet(boolean value) {
    if (!value) {
      this.invest_special_account = null;
    }
  }

  public ResultInfoStruct getRetInfo() {
    return this.retInfo;
  }

  public BankSignResultStruct setRetInfo(ResultInfoStruct retInfo) {
    this.retInfo = retInfo;
    return this;
  }

  public void unsetRetInfo() {
    this.retInfo = null;
  }

  /** Returns true if field retInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetRetInfo() {
    return this.retInfo != null;
  }

  public void setRetInfoIsSet(boolean value) {
    if (!value) {
      this.retInfo = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case INVEST_SPECIAL_ACCOUNT:
      if (value == null) {
        unsetInvest_special_account();
      } else {
        setInvest_special_account((String)value);
      }
      break;

    case RET_INFO:
      if (value == null) {
        unsetRetInfo();
      } else {
        setRetInfo((ResultInfoStruct)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case INVEST_SPECIAL_ACCOUNT:
      return getInvest_special_account();

    case RET_INFO:
      return getRetInfo();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case INVEST_SPECIAL_ACCOUNT:
      return isSetInvest_special_account();
    case RET_INFO:
      return isSetRetInfo();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof BankSignResultStruct)
      return this.equals((BankSignResultStruct)that);
    return false;
  }

  public boolean equals(BankSignResultStruct that) {
    if (that == null)
      return false;

    boolean this_present_invest_special_account = true && this.isSetInvest_special_account();
    boolean that_present_invest_special_account = true && that.isSetInvest_special_account();
    if (this_present_invest_special_account || that_present_invest_special_account) {
      if (!(this_present_invest_special_account && that_present_invest_special_account))
        return false;
      if (!this.invest_special_account.equals(that.invest_special_account))
        return false;
    }

    boolean this_present_retInfo = true && this.isSetRetInfo();
    boolean that_present_retInfo = true && that.isSetRetInfo();
    if (this_present_retInfo || that_present_retInfo) {
      if (!(this_present_retInfo && that_present_retInfo))
        return false;
      if (!this.retInfo.equals(that.retInfo))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(BankSignResultStruct other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetInvest_special_account()).compareTo(other.isSetInvest_special_account());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInvest_special_account()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.invest_special_account, other.invest_special_account);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRetInfo()).compareTo(other.isSetRetInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRetInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.retInfo, other.retInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("BankSignResultStruct(");
    boolean first = true;

    sb.append("invest_special_account:");
    if (this.invest_special_account == null) {
      sb.append("null");
    } else {
      sb.append(this.invest_special_account);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("retInfo:");
    if (this.retInfo == null) {
      sb.append("null");
    } else {
      sb.append(this.retInfo);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (invest_special_account == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'invest_special_account' was not present! Struct: " + toString());
    }
    if (retInfo == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'retInfo' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (retInfo != null) {
      retInfo.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BankSignResultStructStandardSchemeFactory implements SchemeFactory {
    public BankSignResultStructStandardScheme getScheme() {
      return new BankSignResultStructStandardScheme();
    }
  }

  private static class BankSignResultStructStandardScheme extends StandardScheme<BankSignResultStruct> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BankSignResultStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // INVEST_SPECIAL_ACCOUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.invest_special_account = iprot.readString();
              struct.setInvest_special_accountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RET_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.retInfo = new ResultInfoStruct();
              struct.retInfo.read(iprot);
              struct.setRetInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BankSignResultStruct struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.invest_special_account != null) {
        oprot.writeFieldBegin(INVEST_SPECIAL_ACCOUNT_FIELD_DESC);
        oprot.writeString(struct.invest_special_account);
        oprot.writeFieldEnd();
      }
      if (struct.retInfo != null) {
        oprot.writeFieldBegin(RET_INFO_FIELD_DESC);
        struct.retInfo.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BankSignResultStructTupleSchemeFactory implements SchemeFactory {
    public BankSignResultStructTupleScheme getScheme() {
      return new BankSignResultStructTupleScheme();
    }
  }

  private static class BankSignResultStructTupleScheme extends TupleScheme<BankSignResultStruct> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BankSignResultStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.invest_special_account);
      struct.retInfo.write(oprot);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BankSignResultStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.invest_special_account = iprot.readString();
      struct.setInvest_special_accountIsSet(true);
      struct.retInfo = new ResultInfoStruct();
      struct.retInfo.read(iprot);
      struct.setRetInfoIsSet(true);
    }
  }

}

