/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tongbaotu.fits.thrift.idl;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ProductAuditItem implements org.apache.thrift.TBase<ProductAuditItem, ProductAuditItem._Fields>, java.io.Serializable, Cloneable, Comparable<ProductAuditItem> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ProductAuditItem");

  private static final org.apache.thrift.protocol.TField PRODUCTID_FIELD_DESC = new org.apache.thrift.protocol.TField("productid", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField OPETYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("opetype", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ProductAuditItemStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ProductAuditItemTupleSchemeFactory());
  }

  public String productid; // required
  public int opetype; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    PRODUCTID((short)1, "productid"),
    OPETYPE((short)2, "opetype");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // PRODUCTID
          return PRODUCTID;
        case 2: // OPETYPE
          return OPETYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __OPETYPE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.PRODUCTID, new org.apache.thrift.meta_data.FieldMetaData("productid", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OPETYPE, new org.apache.thrift.meta_data.FieldMetaData("opetype", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ProductAuditItem.class, metaDataMap);
  }

  public ProductAuditItem() {
  }

  public ProductAuditItem(
    String productid,
    int opetype)
  {
    this();
    this.productid = productid;
    this.opetype = opetype;
    setOpetypeIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ProductAuditItem(ProductAuditItem other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetProductid()) {
      this.productid = other.productid;
    }
    this.opetype = other.opetype;
  }

  public ProductAuditItem deepCopy() {
    return new ProductAuditItem(this);
  }

  @Override
  public void clear() {
    this.productid = null;
    setOpetypeIsSet(false);
    this.opetype = 0;
  }

  public String getProductid() {
    return this.productid;
  }

  public ProductAuditItem setProductid(String productid) {
    this.productid = productid;
    return this;
  }

  public void unsetProductid() {
    this.productid = null;
  }

  /** Returns true if field productid is set (has been assigned a value) and false otherwise */
  public boolean isSetProductid() {
    return this.productid != null;
  }

  public void setProductidIsSet(boolean value) {
    if (!value) {
      this.productid = null;
    }
  }

  public int getOpetype() {
    return this.opetype;
  }

  public ProductAuditItem setOpetype(int opetype) {
    this.opetype = opetype;
    setOpetypeIsSet(true);
    return this;
  }

  public void unsetOpetype() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __OPETYPE_ISSET_ID);
  }

  /** Returns true if field opetype is set (has been assigned a value) and false otherwise */
  public boolean isSetOpetype() {
    return EncodingUtils.testBit(__isset_bitfield, __OPETYPE_ISSET_ID);
  }

  public void setOpetypeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __OPETYPE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case PRODUCTID:
      if (value == null) {
        unsetProductid();
      } else {
        setProductid((String)value);
      }
      break;

    case OPETYPE:
      if (value == null) {
        unsetOpetype();
      } else {
        setOpetype((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case PRODUCTID:
      return getProductid();

    case OPETYPE:
      return Integer.valueOf(getOpetype());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case PRODUCTID:
      return isSetProductid();
    case OPETYPE:
      return isSetOpetype();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ProductAuditItem)
      return this.equals((ProductAuditItem)that);
    return false;
  }

  public boolean equals(ProductAuditItem that) {
    if (that == null)
      return false;

    boolean this_present_productid = true && this.isSetProductid();
    boolean that_present_productid = true && that.isSetProductid();
    if (this_present_productid || that_present_productid) {
      if (!(this_present_productid && that_present_productid))
        return false;
      if (!this.productid.equals(that.productid))
        return false;
    }

    boolean this_present_opetype = true;
    boolean that_present_opetype = true;
    if (this_present_opetype || that_present_opetype) {
      if (!(this_present_opetype && that_present_opetype))
        return false;
      if (this.opetype != that.opetype)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(ProductAuditItem other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetProductid()).compareTo(other.isSetProductid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProductid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.productid, other.productid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOpetype()).compareTo(other.isSetOpetype());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOpetype()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.opetype, other.opetype);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ProductAuditItem(");
    boolean first = true;

    sb.append("productid:");
    if (this.productid == null) {
      sb.append("null");
    } else {
      sb.append(this.productid);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("opetype:");
    sb.append(this.opetype);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (productid == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'productid' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'opetype' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ProductAuditItemStandardSchemeFactory implements SchemeFactory {
    public ProductAuditItemStandardScheme getScheme() {
      return new ProductAuditItemStandardScheme();
    }
  }

  private static class ProductAuditItemStandardScheme extends StandardScheme<ProductAuditItem> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ProductAuditItem struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // PRODUCTID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.productid = iprot.readString();
              struct.setProductidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // OPETYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.opetype = iprot.readI32();
              struct.setOpetypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetOpetype()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'opetype' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ProductAuditItem struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.productid != null) {
        oprot.writeFieldBegin(PRODUCTID_FIELD_DESC);
        oprot.writeString(struct.productid);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(OPETYPE_FIELD_DESC);
      oprot.writeI32(struct.opetype);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ProductAuditItemTupleSchemeFactory implements SchemeFactory {
    public ProductAuditItemTupleScheme getScheme() {
      return new ProductAuditItemTupleScheme();
    }
  }

  private static class ProductAuditItemTupleScheme extends TupleScheme<ProductAuditItem> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ProductAuditItem struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.productid);
      oprot.writeI32(struct.opetype);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ProductAuditItem struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.productid = iprot.readString();
      struct.setProductidIsSet(true);
      struct.opetype = iprot.readI32();
      struct.setOpetypeIsSet(true);
    }
  }

}

