/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.tongbaotu.fits.thrift.idl;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TransferInfoStruct implements org.apache.thrift.TBase<TransferInfoStruct, TransferInfoStruct._Fields>, java.io.Serializable, Cloneable, Comparable<TransferInfoStruct> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TransferInfoStruct");

  private static final org.apache.thrift.protocol.TField INVESTOR_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("investorID", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField AMOUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("amount", org.apache.thrift.protocol.TType.DOUBLE, (short)2);
  private static final org.apache.thrift.protocol.TField CURRENCY_FIELD_DESC = new org.apache.thrift.protocol.TField("currency", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField TRANSFER_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("transferType", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField INVEST_SPECIAL_ACCOUNT_FIELD_DESC = new org.apache.thrift.protocol.TField("invest_special_account", org.apache.thrift.protocol.TType.STRING, (short)5);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TransferInfoStructStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TransferInfoStructTupleSchemeFactory());
  }

  public String investorID; // required
  public double amount; // required
  public int currency; // required
  public int transferType; // required
  public String invest_special_account; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    INVESTOR_ID((short)1, "investorID"),
    AMOUNT((short)2, "amount"),
    CURRENCY((short)3, "currency"),
    TRANSFER_TYPE((short)4, "transferType"),
    INVEST_SPECIAL_ACCOUNT((short)5, "invest_special_account");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // INVESTOR_ID
          return INVESTOR_ID;
        case 2: // AMOUNT
          return AMOUNT;
        case 3: // CURRENCY
          return CURRENCY;
        case 4: // TRANSFER_TYPE
          return TRANSFER_TYPE;
        case 5: // INVEST_SPECIAL_ACCOUNT
          return INVEST_SPECIAL_ACCOUNT;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __AMOUNT_ISSET_ID = 0;
  private static final int __CURRENCY_ISSET_ID = 1;
  private static final int __TRANSFERTYPE_ISSET_ID = 2;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.INVESTOR_ID, new org.apache.thrift.meta_data.FieldMetaData("investorID", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.AMOUNT, new org.apache.thrift.meta_data.FieldMetaData("amount", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.CURRENCY, new org.apache.thrift.meta_data.FieldMetaData("currency", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.TRANSFER_TYPE, new org.apache.thrift.meta_data.FieldMetaData("transferType", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.INVEST_SPECIAL_ACCOUNT, new org.apache.thrift.meta_data.FieldMetaData("invest_special_account", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TransferInfoStruct.class, metaDataMap);
  }

  public TransferInfoStruct() {
  }

  public TransferInfoStruct(
    String investorID,
    double amount,
    int currency,
    int transferType,
    String invest_special_account)
  {
    this();
    this.investorID = investorID;
    this.amount = amount;
    setAmountIsSet(true);
    this.currency = currency;
    setCurrencyIsSet(true);
    this.transferType = transferType;
    setTransferTypeIsSet(true);
    this.invest_special_account = invest_special_account;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TransferInfoStruct(TransferInfoStruct other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetInvestorID()) {
      this.investorID = other.investorID;
    }
    this.amount = other.amount;
    this.currency = other.currency;
    this.transferType = other.transferType;
    if (other.isSetInvest_special_account()) {
      this.invest_special_account = other.invest_special_account;
    }
  }

  public TransferInfoStruct deepCopy() {
    return new TransferInfoStruct(this);
  }

  @Override
  public void clear() {
    this.investorID = null;
    setAmountIsSet(false);
    this.amount = 0.0;
    setCurrencyIsSet(false);
    this.currency = 0;
    setTransferTypeIsSet(false);
    this.transferType = 0;
    this.invest_special_account = null;
  }

  public String getInvestorID() {
    return this.investorID;
  }

  public TransferInfoStruct setInvestorID(String investorID) {
    this.investorID = investorID;
    return this;
  }

  public void unsetInvestorID() {
    this.investorID = null;
  }

  /** Returns true if field investorID is set (has been assigned a value) and false otherwise */
  public boolean isSetInvestorID() {
    return this.investorID != null;
  }

  public void setInvestorIDIsSet(boolean value) {
    if (!value) {
      this.investorID = null;
    }
  }

  public double getAmount() {
    return this.amount;
  }

  public TransferInfoStruct setAmount(double amount) {
    this.amount = amount;
    setAmountIsSet(true);
    return this;
  }

  public void unsetAmount() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __AMOUNT_ISSET_ID);
  }

  /** Returns true if field amount is set (has been assigned a value) and false otherwise */
  public boolean isSetAmount() {
    return EncodingUtils.testBit(__isset_bitfield, __AMOUNT_ISSET_ID);
  }

  public void setAmountIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __AMOUNT_ISSET_ID, value);
  }

  public int getCurrency() {
    return this.currency;
  }

  public TransferInfoStruct setCurrency(int currency) {
    this.currency = currency;
    setCurrencyIsSet(true);
    return this;
  }

  public void unsetCurrency() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __CURRENCY_ISSET_ID);
  }

  /** Returns true if field currency is set (has been assigned a value) and false otherwise */
  public boolean isSetCurrency() {
    return EncodingUtils.testBit(__isset_bitfield, __CURRENCY_ISSET_ID);
  }

  public void setCurrencyIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __CURRENCY_ISSET_ID, value);
  }

  public int getTransferType() {
    return this.transferType;
  }

  public TransferInfoStruct setTransferType(int transferType) {
    this.transferType = transferType;
    setTransferTypeIsSet(true);
    return this;
  }

  public void unsetTransferType() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TRANSFERTYPE_ISSET_ID);
  }

  /** Returns true if field transferType is set (has been assigned a value) and false otherwise */
  public boolean isSetTransferType() {
    return EncodingUtils.testBit(__isset_bitfield, __TRANSFERTYPE_ISSET_ID);
  }

  public void setTransferTypeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TRANSFERTYPE_ISSET_ID, value);
  }

  public String getInvest_special_account() {
    return this.invest_special_account;
  }

  public TransferInfoStruct setInvest_special_account(String invest_special_account) {
    this.invest_special_account = invest_special_account;
    return this;
  }

  public void unsetInvest_special_account() {
    this.invest_special_account = null;
  }

  /** Returns true if field invest_special_account is set (has been assigned a value) and false otherwise */
  public boolean isSetInvest_special_account() {
    return this.invest_special_account != null;
  }

  public void setInvest_special_accountIsSet(boolean value) {
    if (!value) {
      this.invest_special_account = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case INVESTOR_ID:
      if (value == null) {
        unsetInvestorID();
      } else {
        setInvestorID((String)value);
      }
      break;

    case AMOUNT:
      if (value == null) {
        unsetAmount();
      } else {
        setAmount((Double)value);
      }
      break;

    case CURRENCY:
      if (value == null) {
        unsetCurrency();
      } else {
        setCurrency((Integer)value);
      }
      break;

    case TRANSFER_TYPE:
      if (value == null) {
        unsetTransferType();
      } else {
        setTransferType((Integer)value);
      }
      break;

    case INVEST_SPECIAL_ACCOUNT:
      if (value == null) {
        unsetInvest_special_account();
      } else {
        setInvest_special_account((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case INVESTOR_ID:
      return getInvestorID();

    case AMOUNT:
      return Double.valueOf(getAmount());

    case CURRENCY:
      return Integer.valueOf(getCurrency());

    case TRANSFER_TYPE:
      return Integer.valueOf(getTransferType());

    case INVEST_SPECIAL_ACCOUNT:
      return getInvest_special_account();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case INVESTOR_ID:
      return isSetInvestorID();
    case AMOUNT:
      return isSetAmount();
    case CURRENCY:
      return isSetCurrency();
    case TRANSFER_TYPE:
      return isSetTransferType();
    case INVEST_SPECIAL_ACCOUNT:
      return isSetInvest_special_account();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TransferInfoStruct)
      return this.equals((TransferInfoStruct)that);
    return false;
  }

  public boolean equals(TransferInfoStruct that) {
    if (that == null)
      return false;

    boolean this_present_investorID = true && this.isSetInvestorID();
    boolean that_present_investorID = true && that.isSetInvestorID();
    if (this_present_investorID || that_present_investorID) {
      if (!(this_present_investorID && that_present_investorID))
        return false;
      if (!this.investorID.equals(that.investorID))
        return false;
    }

    boolean this_present_amount = true;
    boolean that_present_amount = true;
    if (this_present_amount || that_present_amount) {
      if (!(this_present_amount && that_present_amount))
        return false;
      if (this.amount != that.amount)
        return false;
    }

    boolean this_present_currency = true;
    boolean that_present_currency = true;
    if (this_present_currency || that_present_currency) {
      if (!(this_present_currency && that_present_currency))
        return false;
      if (this.currency != that.currency)
        return false;
    }

    boolean this_present_transferType = true;
    boolean that_present_transferType = true;
    if (this_present_transferType || that_present_transferType) {
      if (!(this_present_transferType && that_present_transferType))
        return false;
      if (this.transferType != that.transferType)
        return false;
    }

    boolean this_present_invest_special_account = true && this.isSetInvest_special_account();
    boolean that_present_invest_special_account = true && that.isSetInvest_special_account();
    if (this_present_invest_special_account || that_present_invest_special_account) {
      if (!(this_present_invest_special_account && that_present_invest_special_account))
        return false;
      if (!this.invest_special_account.equals(that.invest_special_account))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(TransferInfoStruct other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetInvestorID()).compareTo(other.isSetInvestorID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInvestorID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.investorID, other.investorID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAmount()).compareTo(other.isSetAmount());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAmount()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.amount, other.amount);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCurrency()).compareTo(other.isSetCurrency());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCurrency()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.currency, other.currency);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTransferType()).compareTo(other.isSetTransferType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTransferType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.transferType, other.transferType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetInvest_special_account()).compareTo(other.isSetInvest_special_account());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInvest_special_account()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.invest_special_account, other.invest_special_account);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TransferInfoStruct(");
    boolean first = true;

    sb.append("investorID:");
    if (this.investorID == null) {
      sb.append("null");
    } else {
      sb.append(this.investorID);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("amount:");
    sb.append(this.amount);
    first = false;
    if (!first) sb.append(", ");
    sb.append("currency:");
    sb.append(this.currency);
    first = false;
    if (!first) sb.append(", ");
    sb.append("transferType:");
    sb.append(this.transferType);
    first = false;
    if (!first) sb.append(", ");
    sb.append("invest_special_account:");
    if (this.invest_special_account == null) {
      sb.append("null");
    } else {
      sb.append(this.invest_special_account);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (investorID == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'investorID' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'amount' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'currency' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'transferType' because it's a primitive and you chose the non-beans generator.
    if (invest_special_account == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'invest_special_account' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TransferInfoStructStandardSchemeFactory implements SchemeFactory {
    public TransferInfoStructStandardScheme getScheme() {
      return new TransferInfoStructStandardScheme();
    }
  }

  private static class TransferInfoStructStandardScheme extends StandardScheme<TransferInfoStruct> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TransferInfoStruct struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // INVESTOR_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.investorID = iprot.readString();
              struct.setInvestorIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // AMOUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.amount = iprot.readDouble();
              struct.setAmountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CURRENCY
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.currency = iprot.readI32();
              struct.setCurrencyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // TRANSFER_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.transferType = iprot.readI32();
              struct.setTransferTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // INVEST_SPECIAL_ACCOUNT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.invest_special_account = iprot.readString();
              struct.setInvest_special_accountIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetAmount()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'amount' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetCurrency()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'currency' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetTransferType()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'transferType' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TransferInfoStruct struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.investorID != null) {
        oprot.writeFieldBegin(INVESTOR_ID_FIELD_DESC);
        oprot.writeString(struct.investorID);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(AMOUNT_FIELD_DESC);
      oprot.writeDouble(struct.amount);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(CURRENCY_FIELD_DESC);
      oprot.writeI32(struct.currency);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TRANSFER_TYPE_FIELD_DESC);
      oprot.writeI32(struct.transferType);
      oprot.writeFieldEnd();
      if (struct.invest_special_account != null) {
        oprot.writeFieldBegin(INVEST_SPECIAL_ACCOUNT_FIELD_DESC);
        oprot.writeString(struct.invest_special_account);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TransferInfoStructTupleSchemeFactory implements SchemeFactory {
    public TransferInfoStructTupleScheme getScheme() {
      return new TransferInfoStructTupleScheme();
    }
  }

  private static class TransferInfoStructTupleScheme extends TupleScheme<TransferInfoStruct> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TransferInfoStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.investorID);
      oprot.writeDouble(struct.amount);
      oprot.writeI32(struct.currency);
      oprot.writeI32(struct.transferType);
      oprot.writeString(struct.invest_special_account);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TransferInfoStruct struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.investorID = iprot.readString();
      struct.setInvestorIDIsSet(true);
      struct.amount = iprot.readDouble();
      struct.setAmountIsSet(true);
      struct.currency = iprot.readI32();
      struct.setCurrencyIsSet(true);
      struct.transferType = iprot.readI32();
      struct.setTransferTypeIsSet(true);
      struct.invest_special_account = iprot.readString();
      struct.setInvest_special_accountIsSet(true);
    }
  }

}

